# Generated by Django 4.1.7 on 2023-03-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1, verbose_name='Удельный вес'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen.categoryrecipe', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес'),
        ),
    ]
