# Generated by Django 4.1.7 on 2023-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gr', 'гр'), ('l', 'л'), ('ml', 'мл'), ('pcs', 'шт')], default='kg', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
