# Generated by Django 4.1.7 on 2023-02-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_remove_product_image_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(to='kitchen.product', verbose_name='Продукты для рецепта'),
        ),
    ]
