# Generated by Django 4.1.7 on 2023-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_product_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstore',
            name='transaction_type_float',
            field=models.FloatField(default=0),
        ),
    ]
