# Generated by Django 4.1.7 on 2023-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_product_name_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(to='kitchen.productforrecipe', verbose_name='Продукты для рецепта'),
        ),
    ]
