# Generated by Django 4.1.7 on 2023-02-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_remove_order_client_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
