# Generated by Django 4.1.7 on 2023-02-19 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_remove_card_name_card_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
    ]
