# Generated by Django 4.1.7 on 2023-02-19 20:09

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_alter_card_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='Дата создания'),
        ),
    ]
